export:
  folder: custom
langcode: en
_core:
  default_config_hash: YS8SFNy6Qff2UEsQ5zXWEj-ABeRS-jCgcHJrXHJhtJ0
profile:
  machine_name: meteo_uniparthenope
  name: 'Meteo Uniparthenope'
  description: 'Regional Center for Marine and Atmospheric Monitoring and Modelling'
