features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 0
  path: 'public://parth-logo-3fasce-cerchio_25x25_favicon.png'
  mimetype: image/png
